# Generated by Django 6.0.2 on 2026-02-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, default='', help_text='Comma-separated interests', max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available_for_pairing',
            field=models.BooleanField(default=False),
        ),
    ]
