# Generated by Django 6.0.2 on 2026-03-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gender_customuser_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='AI bot account'),
        ),
        migrations.CreateModel(
            name='AIPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_role', models.CharField(choices=[('student', 'Student Bot'), ('teacher', 'Teacher Bot')], default='student', max_length=10)),
                ('display_name', models.CharField(max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('specialty', models.CharField(blank=True, help_text='e.g. Python, Algorithms, Web Dev', max_length=100)),
                ('personality_prompt', models.TextField(help_text="System prompt for generating content in this bot's voice")),
                ('coding_style', models.CharField(default='balanced', help_text='e.g. clean, clever, verbose, minimal', max_length=50)),
                ('skill_level', models.FloatField(default=0.5)),
                ('posts_per_day', models.IntegerField(default=2)),
                ('comments_per_day', models.IntegerField(default=5)),
                ('blogs_per_week', models.IntegerField(default=1)),
                ('teaches_subject', models.CharField(blank=True, help_text='Subject area for teacher bots', max_length=100)),
                ('quiz_difficulty', models.CharField(default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_personality', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Personalities',
            },
        ),
    ]
