# Generated by Django 6.0.2 on 2026-02-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(help_text='Judge0 language ID')),
                ('language_name', models.CharField(default='Python', max_length=50)),
                ('source_code', models.TextField()),
                ('stdin', models.TextField(blank=True, default='')),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('compile_output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded')], default='pending', max_length=20)),
                ('status_description', models.CharField(blank=True, default='', max_length=100)),
                ('execution_time', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Kilobytes', null=True)),
                ('judge0_token', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
