# Generated by Django 6.0.2 on 2026-02-13 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Problem description in Markdown')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('time_limit_minutes', models.IntegerField(default=30)),
                ('starter_python', models.TextField(blank=True, default='')),
                ('starter_javascript', models.TextField(blank=True, default='')),
                ('starter_cpp', models.TextField(blank=True, default='')),
                ('starter_java', models.TextField(blank=True, default='')),
                ('hint', models.TextField(blank=True, default='', help_text='Optional hint for the student')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BattleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], default='in_progress', max_length=15)),
                ('attempts_count', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_sessions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='compiler.codechallenge')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('language_id', models.IntegerField()),
                ('language_name', models.CharField(default='Python', max_length=50)),
                ('passed_tests', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('all_passed', models.BooleanField(default=False)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='compiler.battlesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='stdin input for this test')),
                ('expected_output', models.TextField(help_text='Expected stdout (whitespace-trimmed)')),
                ('is_sample', models.BooleanField(default=False, help_text='Sample tests are visible to the student before submitting')),
                ('order', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='compiler.codechallenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
