# Generated by Django 6.0.2 on 2026-02-13 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_codechallenge_battlesession_battlesubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PvPBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('countdown', 'Countdown'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=15)),
                ('p1_passed', models.IntegerField(default=0)),
                ('p1_total', models.IntegerField(default=0)),
                ('p1_time', models.FloatField(default=0.0)),
                ('p2_passed', models.IntegerField(default=0)),
                ('p2_total', models.IntegerField(default=0)),
                ('p2_time', models.FloatField(default=0.0)),
                ('difficulty', models.CharField(default='easy', max_length=10)),
                ('points_awarded', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvp_battles', to='compiler.codechallenge')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvp_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvp_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
