# Generated by Django 6.0.2 on 2026-02-13 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_pvpbattle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('difficulty', models.CharField(max_length=10)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_features', to='compiler.codechallenge')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('solve_time', models.FloatField(blank=True, help_text='Seconds to solve', null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='compiler.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'daily')},
            },
        ),
    ]
