# Generated by Django 6.0.2 on 2026-02-13 23:46

import compiler.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_dailychallenge_dailysubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('max_players', models.IntegerField(choices=[(4, '4 Players'), (8, '8 Players'), (16, '16 Players')], default=8)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open for joining'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('join_code', models.CharField(default=compiler.models._gen_join_code, max_length=6, unique=True)),
                ('prize_points', models.IntegerField(default=100, help_text='Rank points for the winner')),
                ('current_round', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tournaments', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('p1_passed', models.IntegerField(default=0)),
                ('p1_total', models.IntegerField(default=0)),
                ('p1_time', models.FloatField(default=0.0)),
                ('p2_passed', models.IntegerField(default=0)),
                ('p2_total', models.IntegerField(default=0)),
                ('p2_time', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('bye', 'Bye')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compiler.codechallenge')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='compiler.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=0)),
                ('eliminated', models.BooleanField(default=False)),
                ('placement', models.IntegerField(blank=True, help_text='1=winner, 2=runner-up, etc.', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='compiler.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seed'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
