# Generated by Django 6.0.2 on 2026-02-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_tournament_tournamentmatch_tournamentparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='elo_bonus',
            field=models.IntegerField(default=25, help_text='ELO bonus for the winner'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='runner_up_points',
            field=models.IntegerField(default=50, help_text='Rank points for the runner-up'),
        ),
    ]
