# Generated by Django 6.0.2 on 2026-02-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_tournament_elo_bonus_tournament_runner_up_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='time_limit_minutes',
            field=models.IntegerField(default=10, help_text='Minutes per match'),
        ),
    ]
