# Generated by Django 6.0.2 on 2026-02-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0010_towerdefensescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleinvite',
            name='difficulty',
            field=models.CharField(default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='battleinvite',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('battle_invite', 'Battle Invitation'), ('battle_accepted', 'Battle Accepted'), ('battle_declined', 'Battle Declined'), ('tournament_start', 'Tournament Starting'), ('achievement', 'Achievement Unlocked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
