# Generated by Django 6.0.2 on 2026-03-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0011_alter_battleinvite_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('countdown', 'Countdown'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=15)),
                ('current_turn', models.IntegerField(default=1, help_text='1 or 2 — whose turn')),
                ('move_count', models.IntegerField(default=0)),
                ('initial_time', models.FloatField(default=300.0, help_text='Starting time per player in seconds')),
                ('p1_time_remaining', models.FloatField(default=300.0)),
                ('p2_time_remaining', models.FloatField(default=300.0)),
                ('turn_started_at', models.DateTimeField(blank=True, null=True)),
                ('shared_code', models.TextField(blank=True, default='')),
                ('p1_lines_written', models.IntegerField(default=0)),
                ('p2_lines_written', models.IntegerField(default=0)),
                ('tests_passed', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('difficulty', models.CharField(default='easy', max_length=10)),
                ('points_awarded', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_battles', to='compiler.codechallenge')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChessMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('line_content', models.TextField()),
                ('time_spent', models.FloatField(default=0.0, help_text='Seconds spent on this move')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='compiler.chessbattle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
    ]
