# Generated by Django 6.0.2 on 2026-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='best_daily_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='daily_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='elo_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='last_daily_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='pvp_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='pvp_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='pvp_wins',
            field=models.IntegerField(default=0),
        ),
    ]
